### ISSUE TITLE
TCP Support

### ISSUE THREAD

**Issue by boneskull** [eclipse/paho.mqtt.javascript#140]
Related to #88 and maybe other issues.

@icraggs Mentions the client should also support TCP sockets in addition to WebSockets.

This is "less important" than #139.

**Comment by ameinhardt** [comment]
my pull request https://github.com/eclipse/paho.mqtt.javascript/pull/158 supports tcp/tls (for chrome app). I this issue is about tcp for node? Maybe that would result in one paho.js build for web, another for node.js?

**Comment by faisalbudiman** [comment]
i want to connecting to tcp://myurl:1884
but console show an error
`mqttws31.js:979 Uncaught DOMException: Failed to construct 'WebSocket': The URL 'ws://[tcp://mchat.mindwave.my]:1884/mqtt' is invalid.
    at ClientImpl.Paho.MQTT.ClientImpl._doConnect (http://localhost/chatsapp/Website/Client/chatweb/assets/js/mqttws31.js:979:18)
    at ClientImpl.Paho.MQTT.ClientImpl.connect (http://localhost/chatsapp/Website/Client/chatweb/assets/js/mqttws31.js:849:9)
    at Client.connect (http://localhost/chatsapp/Website/Client/chatweb/assets/js/mqttws31.js:1799:11)
    at http://localhost/chatsapp/Website/Client/chatweb/assets/js/app.js:303:10`

anyone can help me please ?
